#!/bin/sh
case $BUTTON in
	1) st -e nmcli device wifi list ;;
	2) st -e nmtui ;;
	3) st -e nvim /home/zeos/Github/dwmblocks/scripts/sb_network ;;
esac

if grep -xq 'up' /sys/class/net/w*/operstate 2>/dev/null ; then
	wifiicon="$(awk '/^\s*w/ { print int($3 * 100 / 70) "% " }' /proc/net/wireless)"
elif grep -xq 'down' /sys/class/net/w*/operstate 2>/dev/null ; then
	grep -xq '0x1003' /sys/class/net/w*/flags && wifiicon="📡 " || wifiicon="❌ "
fi

network="$(nmcli -t -f active,ssid dev wifi | grep '^yes' | cut -d: -f2 )"

output="$(printf "%s%s%s\n" "$network " "$wifiicon" "$(sed "s/down/❎/;s/up/🌐/" /sys/class/net/e*/operstate 2>/dev/null)" "$(sed "s/.*/🔒/" /sys/class/net/tun*/operstate 2>/dev/null)")"
echo "${output}"

